### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/phpipam/functions/scripts/nmapScanner.php on line 12

### ISSUE THREAD

**Issue by Tipsmark** [litebito/phpipam-scripts#1]
I get the following error - have followed the guide, but so far no luck.  Any ideas?

[root@linuxhost scripts]# php nmapScanner.php
[2018-11-25 07:11:02][INFO]Starting nmapScanner.php ... [3.32kb]
* About to connect() to linuxhost.domain.local port 443 (#0)
*   Trying 10.1.5.27...
* Connected to linuxhost.domain.local (10.1.5.27) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=linuxhost.domain.local
*       start date: Nov 01 00:00:00 2010 GMT
*       expire date: Aug 04 12:00:00 2030 GMT
*       common name: linuxhost.domain.local
*       issuer: CN=RapidSSL RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /api/nmapScanner/user/ HTTP/1.1
User-Agent: phpipam-api php class
Host: linuxhost.domain.local
Accept: */*
Authorization: Basic YWRtaW35eDNQVDlxIO1h
Content-Length: -1
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad request
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
<
* Closing connection 0
[2018-11-25 07:11:02][DEBUG]Response Headers ... [19.51kb]
[2018-11-25 07:11:02][DEBUG] [19.51kb]
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/phpipam/functions/scripts/nmapScanner.php on line 128
[2018-11-25 07:11:02][INFO]All done! [19.6kb]

**Comment by litebito** [comment]
Hi,

it looks like the connection is not successful. I never got SSL to work.
try creating an apikey with "crypt" in IPAM in stead of ssl

**Comment by Tipsmark** [comment]
I tried with crypt, using API key and just "" as user/pwd - still the same.
Could you paste an example of your class.phpipam-api.php and your api-config.php.

**Comment by Tipsmark** [comment]
can anyone paste a functional set of config files?

**Comment by litebito** [comment]
I updated the script and config file to work with 1.5.0 on php 7.4
